version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.10

    working_directory: ~/

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install -r requirements-dev.txt
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
