# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('full', imagekit.models.fields.ProcessedImageField(upload_to='images/blog/')),
            ],
        ),
    ]
